apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-scheduler-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kube-scheduler-operator
  template:
    metadata:
      labels:
        name: kube-scheduler-operator
    spec:
      containers:
        - name: kube-scheduler-operator
          image: docker.io/aveshagarwal/kube-scheduler-operator
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - kube-scheduler-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "kube-scheduler-operator"
